name: brute_force_tester
description: contoh penerapan brute force di dart.
version: 1.0.0
# homepage: https://localhost/

environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
